### ISSUE TITLE
[Request] Waveshare 1.44" LCD display HAT

### ISSUE THREAD

**Issue by a2** [PiSugar/pisugar-case-pihat-cap#2]
The 1.44" LCD display HAT has the same physical dimensions as the 1.3" LCD display HAT model that is already in the repo. I believe the only thing different is the size and placement of the screen on the board. I know this because I accidentally printed the 1.3" LCD cap for my 1.44" LCD model and everything fit well, minus the display.

Would it be possible to edit the model file for this _slightly_ different configuration? The STL file in the repo seems to be one big object, rather than several smaller layers. (I tried to do it myself before reaching out.)

Thank you for your consideration.

**Comment by brentrealbt** [comment]
I would like to get the same. I'd also like to see how you put the pieces together @a2 if you could send me a picture from the side view it would be appreciated.

@a2 - adjustments could be made through tinkercad.com for the display, I'd be happy to try if you could send me a picture of the stack of your pi and hats.

**Comment by a2** [comment]
@brentrealbt Here are some pictures of my setup:

<img src="https://user-images.githubusercontent.com/241156/75690648-88a28b80-5ca3-11ea-9af6-71c2362fc6ad.jpeg" width="300" />
<img src="https://user-images.githubusercontent.com/241156/75690653-89d3b880-5ca3-11ea-916f-cc0100186763.jpeg" width="300" />
<img src="https://user-images.githubusercontent.com/241156/75690677-91935d00-5ca3-11ea-8ac5-1939cc72184a.jpeg" width="300" />

**Comment by JdaieLin** [comment]
I will made some adjustments to fit 1.44 LCD in this week. Can you send me the dimensions of this phat?


In fact I had bought this phat before and returned it because it is only 128x128 in resolution but the 1.3inch one is 240x240...

------------------ Original ------------------

**Comment by brentrealbt** [comment]
Apologies for the delay. The hat is the 6.5cm x 3cm in size. On the left by the joystick there is 1.3cm before the screen ribbon starts, and another 0.5cm of space with the ribbon and on the right there is 1.5cm. The screen after the ribbon is about 3cm in width.

**Comment by a2** [comment]
Thanks, @brentrealbt. I put my 1.44" LCD pHAT in a box somewhere and I wasn't able to properly look for it yet.

**Comment by JdaieLin** [comment]
Hi everyone,
I have updated the cap for 1.44inch LCD. Please see:
https://github.com/PiSugar/pisugar-case-pihat-cap/tree/master/1.44inch_lcd_cap

**Comment by a2** [comment]
Did anyone ever get this printed?

**Comment by rezzorix** [comment]
I printed it on Ender3 v2 - the updated 1.44inch LCD cap works.
